import type { ClaimData } from '@/types'

export const sampleClaimsData: ClaimData[] = [
  {
    id: 'claim-001',
    claimNumber: 'CLM-2024-001',
    patientName: 'Ahmed Al-Rashid',
    providerId: 'bupa-saudi',
    providerName: 'Bupa Arabia',
    serviceDate: '2024-01-15',
    submissionDate: '2024-01-16',
    amount: 1500,
    status: 'rejected',
    rejectionReason: 'Prior authorization required for this procedure',
    rejectionCategory: 'medical',
    rejectionSubcategory: 'Prior Authorization',
    processingTime: 2,
    diagnosisCode: 'M79.9',
    procedureCode: '29825',
    membershipNumber: 'MEM-001',
    policyNumber: 'POL-001'
  },
  {
    id: 'claim-002',
    claimNumber: 'CLM-2024-002',
    patientName: 'Fatima Al-Zahra',
    providerId: 'tawuniya',
    providerName: 'Tawuniya',
    serviceDate: '2024-01-14',
    submissionDate: '2024-01-15',
    amount: 800,
    status: 'rejected',
    rejectionReason: 'Invalid diagnosis code provided',
    rejectionCategory: 'technical',
    rejectionSubcategory: 'Diagnosis Coding',
    processingTime: 1,
    diagnosisCode: 'INVALID',
    procedureCode: '99213',
    membershipNumber: 'MEM-002',
    policyNumber: 'POL-002'
  },
  {
    id: 'claim-003',
    claimNumber: 'CLM-2024-003',
    patientName: 'Mohammed Al-Fahad',
    providerId: 'bupa-saudi',
    providerName: 'Bupa Arabia',
    serviceDate: '2024-01-13',
    submissionDate: '2024-01-14',
    amount: 2200,
    status: 'approved',
    processingTime: 3,
    diagnosisCode: 'I25.9',
    procedureCode: '93000',
    membershipNumber: 'MEM-003',
    policyNumber: 'POL-003'
  },
  {
    id: 'claim-004',
    claimNumber: 'CLM-2024-004',
    patientName: 'Sara Al-Otaibi',
    providerId: 'tawuniya',
    providerName: 'Tawuniya',
    serviceDate: '2024-01-12',
    submissionDate: '2024-01-13',
    amount: 950,
    status: 'rejected',
    rejectionReason: 'Missing required documentation',
    rejectionCategory: 'technical',
    rejectionSubcategory: 'Documentation',
    processingTime: 2,
    diagnosisCode: 'J44.1',
    procedureCode: '94010',
    membershipNumber: 'MEM-004',
    policyNumber: 'POL-004'
  },
  {
    id: 'claim-005',
    claimNumber: 'CLM-2024-005',
    patientName: 'Abdullah Al-Mansouri',
    providerId: 'bupa-saudi',
    providerName: 'Bupa Arabia',
    serviceDate: '2024-01-11',
    submissionDate: '2024-01-12',
    amount: 3500,
    status: 'rejected',
    rejectionReason: 'Treatment not medically necessary according to clinical guidelines',
    rejectionCategory: 'medical',
    rejectionSubcategory: 'Medical Necessity',
    processingTime: 4,
    diagnosisCode: 'Z01.411',
    procedureCode: '76700',
    membershipNumber: 'MEM-005',
    policyNumber: 'POL-005'
  },
  {
    id: 'claim-006',
    claimNumber: 'CLM-2024-006',
    patientName: 'Layla Al-Harbi',
    providerId: 'tawuniya',
    providerName: 'Tawuniya',
    serviceDate: '2024-01-10',
    submissionDate: '2024-01-11',
    amount: 1200,
    status: 'pending',
    processingTime: 5,
    diagnosisCode: 'N39.0',
    procedureCode: '87086',
    membershipNumber: 'MEM-006',
    policyNumber: 'POL-006'
  },
  {
    id: 'claim-007',
    claimNumber: 'CLM-2024-007',
    patientName: 'Omar Al-Dosari',
    providerId: 'bupa-saudi',
    providerName: 'Bupa Arabia',
    serviceDate: '2024-01-09',
    submissionDate: '2024-01-10',
    amount: 750,
    status: 'rejected',
    rejectionReason: 'System timeout during processing - please resubmit',
    rejectionCategory: 'technical',
    rejectionSubcategory: 'System Integration',
    processingTime: 1,
    diagnosisCode: 'K59.00',
    procedureCode: '45378',
    membershipNumber: 'MEM-007',
    policyNumber: 'POL-007'
  },
  {
    id: 'claim-008',
    claimNumber: 'CLM-2024-008',
    patientName: 'Aisha Al-Qahtani',
    providerId: 'tawuniya',
    providerName: 'Tawuniya',
    serviceDate: '2024-01-08',
    submissionDate: '2024-01-09',
    amount: 1800,
    status: 'approved',
    processingTime: 2,
    diagnosisCode: 'E11.9',
    procedureCode: '82947',
    membershipNumber: 'MEM-008',
    policyNumber: 'POL-008'
  },
  {
    id: 'claim-009',
    claimNumber: 'CLM-2024-009',
    patientName: 'Khalid Al-Mutairi',
    providerId: 'bupa-saudi',
    providerName: 'Bupa Arabia',
    serviceDate: '2024-01-07',
    submissionDate: '2024-01-08',
    amount: 4200,
    status: 'rejected',
    rejectionReason: 'Service not covered under Essential Benefits Package',
    rejectionCategory: 'medical',
    rejectionSubcategory: 'Coverage Limitation',
    processingTime: 3,
    diagnosisCode: 'Z51.11',
    procedureCode: '96413',
    membershipNumber: 'MEM-009',
    policyNumber: 'POL-009'
  },
  {
    id: 'claim-010',
    claimNumber: 'CLM-2024-010',
    patientName: 'Nadia Al-Shehri',
    providerId: 'tawuniya',
    providerName: 'Tawuniya',
    serviceDate: '2024-01-06',
    submissionDate: '2024-01-07',
    amount: 680,
    status: 'rejected',
    rejectionReason: 'Incorrect billing code used for procedure',
    rejectionCategory: 'technical',
    rejectionSubcategory: 'Billing Codes',
    processingTime: 1,
    diagnosisCode: 'H52.4',
    procedureCode: 'INVALID_CODE',
    membershipNumber: 'MEM-010',
    policyNumber: 'POL-010'
  }
]